### ISSUE TITLE
Dax client can not be cast to dynamodbiface.dynamodbapi after 1.25.40

### ISSUE THREAD

**Issue by ardaguclu** [aws/aws-dax-go#21]
In the service package, there is;

`var _ dynamodbiface.DynamoDBAPI = (*Dax)(nil)`

After aws-sdk-go 1.25.40 version has been released, Dax started not being casted to dynamodbiface.dynamodbapi anymore. 

For that reason, I opened PR for this issue;

https://github.com/aws/aws-dax-go/pull/20

**Comment by VasilyFomin** [comment]
Thank you for the contribution, I merged the PR.

**Comment by cfortuner** [comment]
I think I'm still seeing issues for this ? 
*Dax does not implement dynamodbiface.DynamoDBAPI (missing DescribeContributorInsights method)

**Comment by VasilyFomin** [comment]
Thanks for reporting, we're going to prioritize the fix.

It's caused by [Release v1.25.43 (2019-11-26)](https://github.com/aws/aws-sdk-go/commit/eed38bc27435018db6c4de52cf8a60f7da3b54dd) which happened yesterday.

**Comment by ezerozen** [comment]
I have the same issue with github.com/aws/aws-dax-go v1.1.4 and github.com/aws/aws-sdk-go v1.28.0

aws-dax-go@v1.1.4/dax/service.go:129:5: cannot use (*Dax)(nil) (type *Dax) as type dynamodbiface.DynamoDBAPI in assignment:
	*Dax does not implement dynamodbiface.DynamoDBAPI (missing DescribeContributorInsights method)

**Comment by dragon9786** [comment]
It seems like the interface requiremnents were satisfied with this commit: https://github.com/aws/aws-dax-go/commit/f18aceacc28942624e5b48d6e7c1538d45956388#diff-8576d07acff0ae4d08c05392d7535ae3 on Decemeber 2nd 2019.

However the latest release `v1.1.4` was from `November 13 2019`
